### ISSUE TITLE
Can this software be installed on my Windows 10?

### ISSUE THREAD

**Issue by pharazone** [iGio90/Dwarf#5] opened 2019-01-05 03:12 UTC
Hi, dude.
    I love this software and I installed it on my Mac. But I wonder if this can be installed on Windows 10? Sorry for my bad English. Thank you.

**Comment by sieunhando** [comment] 2019-01-05 03:19
Yes, you can.

**Comment by iGio90** [comment] 2019-01-05 07:09
Hi! Yes is multi platform! Should works fine on win too but let me know for issues!

**Comment by pharazone** [comment] 2019-01-05 08:34
hey, here comes some issues on Windows……seem like keystone problems...
![image](https://user-images.githubusercontent.com/11215634/50722300-cb042300-1107-11e9-9f62-21f1f38aa641.png)

**Comment by iGio90** [comment] 2019-01-05 08:37
-> http://www.keystone-engine.org/download/
install from here

**Comment by nrmv** [comment] 2019-01-20 07:03
Аfter installing keystone, there is a problem with the scrypt
![Error](https://i.imgur.com/JL4o3Fk.png)

**Comment by nrmv** [comment] 2019-01-20 08:10
![image](https://user-images.githubusercontent.com/13987951/51436741-e5abcf80-1ca3-11e9-9a58-b1a2db3a061f.png)
![image](https://user-images.githubusercontent.com/13987951/51436746-ee9ca100-1ca3-11e9-97eb-e99778166843.png)

**Comment by nrmv** [comment] 2019-01-20 08:14
Python 3.6

![image](https://user-images.githubusercontent.com/13987951/51436771-7a163200-1ca4-11e9-83fb-c96dd21a5288.png)

**Comment by nrmv** [comment] 2019-01-20 09:01
> For the scrypt Error
> Read the Errors - OpenSSL is missing
> Make sure VC Compiler can find the OpenSSL Headers
> Its looking in c:\OpenSSL-Win64\include
> 
> http://slproweb.com/products/Win32OpenSSL.html
> Needs -> Win64 OpenSSL v1.0.2q Package
> 
> 1.1.x Package have different LibNames
> 
> 
> the last one with the white Window.
> Its saying adb is missing (sometimes or with debugger).
> Make sure Path to adb.ex is in PATH

It worked, but the application also freeze. 

![image](https://user-images.githubusercontent.com/13987951/51437142-04fa2b00-1cab-11e9-8916-ec5ff645a06d.png)
![image](https://user-images.githubusercontent.com/13987951/51437134-e09e4e80-1caa-11e9-9cbc-dfc2bc98b1e8.png)

**Comment by iGio90** [comment] 2019-01-20 09:31
Let me know if you came up with something! Unfortunately I have no windows box to test... I'll setup a VM soon

**Comment by iGio90** [comment] 2019-01-20 09:32
You can use our slack as well! There is people running it on windows that can help with tests

**Comment by PinkiePieStyle** [comment] 2019-01-20 09:42
Ok im using cmd as shell on windows not powershell but think thats not the Problem.

Removed adb from system vars
white window appears

in cmd then 
D:\git-repos\Dwarf>set PATH=%PATH%;D:\AndroidSDK\platform-tools\
D:\git-repos\Dwarf>python dwarf.py

and it works fine again

**Comment by nrmv** [comment] 2019-01-20 09:47
> Ok im using cmd as shell on windows not powershell but think thats not the Problem.
> 
> Removed adb from system vars
> white window appears
> 
> in cmd then
> D:\git-repos\Dwarf>set PATH=%PATH%;D:\AndroidSDK\platform-tools
> D:\git-repos\Dwarf>python dwarf.py
> 
> and it works fine again

Maybe there is a problem in the NoxPlayer?

![image](https://user-images.githubusercontent.com/13987951/51437581-47bf0180-1cb1-11e9-956d-9aebb7fb9592.png)
![image](https://user-images.githubusercontent.com/13987951/51437592-5a393b00-1cb1-11e9-8891-4820a070389d.png)

**Comment by sieunhando** [comment] 2019-01-20 09:49
I think the problem is your emulator. Try Genymotion or android devices.

**Comment by PinkiePieStyle** [comment] 2019-01-20 09:52
The adb stuff should not appear in console it should be redirected to the script
utils.py do_shell_command

**Comment by iGio90** [comment] 2019-01-20 09:52
Yes. It's x86. You'll find some if else around which checks only 'arm' or 'arm64'

**Comment by iGio90** [comment] 2019-01-20 09:54
It is well redirected in osx/linux

**Comment by PinkiePieStyle** [comment] 2019-01-20 10:03
Ok it does not work with the adb from nox dir can reproduce it now.
Use the real Android SDK and its adb

**Comment by iGio90** [comment] 2019-01-20 10:05
Yeah but would be better to know why? Maybe try to use:
adb shell su -c id
On the nox adb

**Comment by sieunhando** [comment] 2019-01-20 10:06
Some emulators use its own adb, you can check it in the emulator installation folder.

**Comment by PinkiePieStyle** [comment] 2019-01-20 10:10
With the adb from nox
![nox1](https://user-images.githubusercontent.com/7350146/51437837-ec3a4700-1ca3-11e9-91cb-f85c0dc710a7.png)

version is empty so it thinks no adb and it is freezing on welcome

**Comment by nrmv** [comment] 2019-01-20 10:19
Genymotion solved the problem, but unfortunately most applications do not work on it.

New problem:
https://i.imgur.com/8dUbRBh.gifv

I execute
`adb push C:\Users\Andrey\Desktop\frida\frida /data/local/tmp/`
But it did not give any results.

**Comment by PinkiePieStyle** [comment] 2019-01-20 10:32
the nox adb is stderr

DirtyFix
utils.py line 28
def do_shell_command(cmd, stdout=subprocess.STDOUT):
    result = subprocess.run(cmd.split(' '), stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if stdout == subprocess.PIPE:
        return result.stdout.decode('utf8')
    if stdout == subprocess.STDOUT:
        return result.stdout.decode('utf8')
    else:
        return ''

**Comment by PinkiePieStyle** [comment] 2019-01-20 11:53
Another one

on Windows there is no "unxz" command so it should simply use pythons lzma
ui_welcome.py line 312
```
if os.name == 'nt':
    import lzma
    with lzma.open('frida.xz') as xz:
        with open('frida', 'wb') as unxz:
            unxz.write(xz.read())
            res = ''
    os.remove('frida.xz')
else:
    res = utils.do_shell_command('unxz frida.xz')
```

**Comment by PinkiePieStyle** [comment] 2019-01-20 13:47
All my changes

```
diff --git a/lib/adb.py b/lib/adb.py
index f9d2321..0bebd8b 100644
--- a/lib/adb.py
+++ b/lib/adb.py
@@ -87,7 +87,9 @@ class Adb(object):
         if not self.adb_available:
             utils.show_message_box('adb not found')
             return None
-        self._do_adb_command('adb shell su -c "mount -o rw,remount /system"')
+        res = self._do_adb_command('adb shell su -c "mount -o rw,remount /system"')
+        if res.index('Permission denied') >= 0:
+            self._do_adb_command('adb shell mount -o rw,remount /system')
 
     def pull(self, path, dest):
         if not self.adb_available:
@@ -105,4 +107,7 @@ class Adb(object):
         if not self.adb_available:
             utils.show_message_box('adb not found')
             return None
-        return self._do_adb_command('adb shell su -c "' + cmd + '"', stdout=stdout)
+        res = self._do_adb_command('adb shell su -c "' + cmd + '"', stdout=stdout)
+        if res.index('Permission denied') >= 0:
+            res = self._do_adb_command('adb shell ' + cmd, stdout=stdout)
+        return res
diff --git a/lib/utils.py b/lib/utils.py
index c6ad9b5..7aa33fd 100644
--- a/lib/utils.py
+++ b/lib/utils.py
@@ -26,9 +26,11 @@ app_icon = None
 
 
 def do_shell_command(cmd, stdout=subprocess.PIPE):
-    result = subprocess.run(cmd.split(' '), stdout=stdout)
+    result = subprocess.run(cmd.split(' '), stdout=stdout, stderr=subprocess.STDOUT)
     if stdout == subprocess.PIPE:
         return result.stdout.decode('utf8')
+    elif stdout == subprocess.STDOUT:
+        return result.stdout.decode('utf8')
     else:
         return ''
 
diff --git a/ui/ui_welcome.py b/ui/ui_welcome.py
index 4b5a59b..3c32258 100644
--- a/ui/ui_welcome.py
+++ b/ui/ui_welcome.py
@@ -136,6 +136,7 @@ class WelcomeUi(QSplitter):
         self.update_device_ui()
         self.update_commits()
         self.update_frida_version()
+        self.on_device_changed()
 
     def update_commits(self):
         data = self.app.get_dwarf().get_git().get_dwarf_commits()
@@ -289,6 +290,12 @@ class WelcomeUi(QSplitter):
 
         self.frida_update_button.setVisible(self.updated_frida_version != local_version)
 
+        #check if frida is running on device or start
+        if(self.updated_frida_version == local_version):
+            res = self.app.get_adb().su('ps | grep frida', stdout=subprocess.PIPE)
+            if(len(res) == 0):
+                self.app.get_adb().su('frida -D', stdout=subprocess.PIPE)
+
     def update_frida(self):
         def _update():
             if os.path.exists('frida'):
@@ -309,16 +316,28 @@ class WelcomeUi(QSplitter):
                     for chunk in r.iter_content(chunk_size=1024):
                         if chunk:
                             f.write(chunk)
-                res = utils.do_shell_command('unxz frida.xz')
+                #on windows no unxz command
+                if os.name == 'nt':
+                    import lzma
+                    with lzma.open('frida.xz') as xz:
+                        with open('frida', 'wb') as unxz:
+                            unxz.write(xz.read())
+                            res = ''
+                    os.remove('frida.xz')
+                else:
+                    res = utils.do_shell_command('unxz frida.xz')
+
                 if len(res) == 0:
                     res = self.app.get_adb().mount_system()
                     if res is None or len(res) == 0:
                         self.app.get_adb().push('frida', '/sdcard/')
-                        self.app.get_adb().su('killall -9 frida', stdout=subprocess.DEVNULL)
-                        self.app.get_adb().su('mv /sdcard/frida /system/xbin/frida', stdout=subprocess.DEVNULL)
-                        self.app.get_adb().su('chmod 755 /system/xbin/frida', stdout=subprocess.DEVNULL)
+                        #self.app.get_adb().su('killall -9 frida', stdout=subprocess.DEVNULL)
+                        #not all have killall command
+                        self.app.get_adb().su('kill -9 $(ps | grep frida | awk { print $2 })', stdout=subprocess.PIPE)
+                        self.app.get_adb().su('cp /sdcard/frida /system/xbin/frida', stdout=subprocess.PIPE)
+                        self.app.get_adb().su('chmod 755 /system/xbin/frida', stdout=subprocess.PIPE)
                         self.update_frida_version()
-                        self.app.get_adb().su('frida -D', stdout=subprocess.DEVNULL)
+                        self.app.get_adb().su('frida -D', stdout=subprocess.PIPE)
                     os.remove('frida')
                 else:
                     os.remove('frida.xz')

```

**Comment by iGio90** [comment] 2019-02-03 23:50
i dont know how come i did totally forget about your message @PinkiePieStyle 
Is there any way you could pr those changes!? just to keep the ownership.. during those days i've fixed (i think) the problem with the stderr as my other friend was having this and we solved it. The one for lzma is still there indeed!

**Comment by PinkiePieStyle** [comment] 2019-02-04 16:46
I've started rewriting a lot of stuff. 
But my local Version is behind master
I'll upload my stuff so take what you want.

It fixes starting freezer from threading in ui_welcome (only main thread should update ui)
Fixes lot of adb stuff and allows more frida stuff (running/stopping)
stdout/stderror is fixed it uses "capture_output=True" so python handles the stdout/stderr
frida update is fixed 
remove:
`utils.do_shell_command('unxz frida.xz')`
pythons lzma works on all os'es

ADB gives now a Message and works only when 3 requirements are true:
"adb: False
dev/emu: False
su: False
root: False
at least 3x True required"
works with all tested devices and emulators fine here

But my changes for the other UI Stuff arent ready so they are not included atm.
The UI suxx on windows...
QTableWidget in panel_memory is replaced with own HexViewer Widget and so on wich runs smoothly and fast here. but all this later when ready...

**Comment by iGio90** [comment] 2019-02-04 17:56
Im porting your changes @PinkiePieStyle ! So far so good, had to edit a couple of stuffs described in commits!

https://github.com/iGio90/Dwarf/tree/PinkiePieStyle

**Comment by PinkiePieStyle** [comment] 2019-02-04 18:02
In ui_welcome it need two changes
replace
update_commits.run()
with
update_commits.start()

and 
dwarf_update_thread.run()
with:
dwarf_update_thread.start()

it should not call run directly

**Comment by iGio90** [comment] 2019-02-04 18:04
if i do those 2 changes
```
iGio90:Dwarf igio90$ python3 dwarf.py 
QThread: Destroyed while thread is still running
Abort trap: 6
iGio90:Dwarf igio90$ 
```

**Comment by iGio90** [comment] 2019-02-04 18:05
its -> update_commits.run()

**Comment by PinkiePieStyle** [comment] 2019-02-04 18:16
its the garbage collector

ui_welcome
```
def update_commits(self):
        if self.update_commits_thread is None:
            self.update_commits_thread = DwarfCommitsThread(app=self.app)
            self.update_commits_thread.on_update_available.connect(self.on_dwarf_isupdate)
            self.update_commits_thread.on_add_commit.connect(self.on_dwarf_commit)
            if not self.update_commits_thread.isRunning():
                self.update_commits_thread.start()

def update_dwarf(self):
        if self.update_dwarf_thread is None:
            self.update_dwarf_thread = DwarfUpdateThread(self.app)
            self.update_dwarf_thread.on_finished.connect(self.on_dwarf_updated)
            self.update_dwarf_thread.on_status_text(self.on_dwarf_status)
            if not self.update_dwarf_thread.isRunning():
                self.update_dwarf_thread.start()
```


and before self.setup_threads()
```
self.update_commits_thread = None
self.update_dwarf_thread = None
```

**Comment by iGio90** [comment] 2019-02-04 18:18
that worked 👯‍♂️

**Comment by iGio90** [comment] 2019-02-04 18:33
Ok so, let's add an if is_emulator there and use the awk version... I wonder why it's not working on nox?

**Comment by PinkiePieStyle** [comment] 2019-02-04 18:34
Have an real device with android 5 rom and there is also no "ps -o" support

**Comment by iGio90** [comment] 2019-02-04 18:35
Ok... Let's just kill -o and grep each of res.split('\n').split(' ') fields

**Comment by PinkiePieStyle** [comment] 2019-02-04 19:01
Tested this part
is_frida_running
result = self.su('ps -A -o comm | grep \'frida\'')

        if result is not None and 'frida' in result.split('\n'):
            return True

its always False

when changed to  self._do_adb_command('adb shell ps | grep \'frida\'')
it runs the command but ('frida' in result.split('\n')) is false

so with awk it runs on all tested devices better

**Comment by PinkiePieStyle** [comment] 2019-02-04 20:00
the subprocess.run() stuff was fixed before some comments above
stderr is redirected to stdout and stdout to pipe

```
def do_shell_command(cmd, timeout=60):
    try:
        # capture output is only supported in py 3.7
        if VERSION.minor == 7:
            result = subprocess.run(cmd.split(' '), timeout=timeout, capture_output=True)
        else:
            result = subprocess.run(cmd.split(' '), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)

        if result.stderr:
            return result.stderr.decode('utf8')

        return result.stdout.decode('utf8')

    except subprocess.TimeoutExpired:
        return None  # todo: timeout doesnt mean cmd failed
```

**Comment by iGio90** [comment] 2019-02-04 21:23
Hey @PinkiePieStyle just got an idea... can you check if your devices respond with a pid to command "adb shell su -c pidof frida" when frida is running? we could use this instead!

**Comment by PinkiePieStyle** [comment] 2019-02-04 21:32
used the command with awk in it directly in shell?

**Comment by iGio90** [comment] 2019-02-04 21:35
a-side that awk doesn't come by default, i had to install busybox but that was not the issue, the command is returning me error even if i run on an adb shell :/ let's just use pidof if it's working on emulators too... we just need the pid in the end!

**Comment by iGio90** [comment] 2019-02-04 21:38
ok I made awk work! but for you it's $2 $9 for me its $1 $4 XD

**Comment by iGio90** [comment] 2019-02-04 21:40
```OnePlus5T:/ # ps -A | grep frida | awk '{print $1 " " $4}'                                                                                                                                                                            
26466 grep
30413 frida
30423 /data/local/tmp/re.frida.server/frida-helper-64
30691 /data/local/tmp/re.frida.server/frida-helper-32
OnePlus5T:/ # ps -A | grep frida | awk '{print $2 " " $9}'                                                                                                                                                                            
0 
0 
0 
0 
OnePlus5T:/ # 
```

**Comment by PinkiePieStyle** [comment] 2019-02-04 21:51
Its Android 8 or greater?
Can you show the output from 'ps' only

This should work on all too but it needs some workaround for killing frida as it needs a pid
```
def is_frida_running(self):
        """ Checks if frida is running
        """
        if not self._adb_available:
            return False

        found = False

        result = self.su('ps | grep \'frida\'')
        result = result.split()

        if 'frida' in result:
            for r in result:
                if 'frida-helper' in r:
                    found = True

        return found
```

**Comment by iGio90** [comment] 2019-02-04 22:00
what about this

https://github.com/iGio90/Dwarf/commit/596c56132a7d692c86fa3bfcd9a8ca3cac561855

**Comment by PinkiePieStyle** [comment] 2019-02-04 22:19
Line 61 needs the ( ) or dev_emu is always false
if res and ('no devices/emulators' or 'device not found') in res:

with the android 4 the ps -A returns nothing only without -A works

seems in 8 it becomes new ps
https://stackoverflow.com/questions/44732749/how-to-make-adb-shell-ps-list-all-processes-in-android-o

**Comment by iGio90** [comment] 2019-02-04 22:34
@PinkiePieStyle review -> https://github.com/iGio90/Dwarf/commit/e7f16799cab8029534e7af3ae9321e43dbd2906a

**Comment by PinkiePieStyle** [comment] 2019-02-04 23:07
found another one
after installing frida on the dev the button needs to enable again
ui_welcome line 657:

```
                if not self.app.get_adb().is_frida_running():
                    self.frida_update_button.setText('start frida')
                    self.frida_update_button.setEnabled(True)
                    self.frida_update_button.setVisible(True)
                else:
                    self.frida_update_button.setText('stop frida')
                    self.frida_update_button.setEnabled(True)
                    self.frida_update_button.setVisible(True)
```

in my repo is my adb.py wich works here with android 4, 5, 7
includes some other fixes too

**Comment by iGio90** [comment] 2019-02-04 23:16
you mean here:

```    
def update_status_label(self, update_text):
        """ sets status text from fridaserver update
        """
                if not self.app.get_adb().is_frida_running():
                    self.frida_update_button.setText('start frida')
                    self.frida_update_button.setEnabled(True)
                    self.frida_update_button.setVisible(True)
                else:
                    self.frida_update_button.setText('stop frida')
                    self.frida_update_button.setEnabled(True)
                    self.frida_update_button.setVisible(True)

        label_text = ('device frida version: {0}\nupdated frida version: {1}'
                      .format(update_text, self.updated_frida_version))

        self.frida_update_label.setText(label_text)
```

**Comment by PinkiePieStyle** [comment] 2019-02-04 23:18
in def update_frida_version(self):
when it updates or installs frida the button gets disabled but then no one can click 'start frida'

**Comment by iGio90** [comment] 2019-02-04 23:31
cool! merged into master with ur last change!

**Comment by PinkiePieStyle** [comment] 2019-02-04 23:31
was there some changes in requirements? merged master in my build but is crying about unicorn now
then on_dwarf_updated should have some "pip3 install -r requirements.txt" stuff too

**Comment by iGio90** [comment] 2019-02-04 23:32
mhhh yeah... i did re-run pipreqs to generate new requirements.txt yesterday i think

**Comment by PinkiePieStyle** [comment] 2019-02-04 23:35
found it 
https://github.com/iGio90/Dwarf/commit/216b2b1c928509115b67071491e57bf4f906bdff#diff-b4ef698db8ca845e5845c4618278f29a

but this breaks the internal dawrf update

**Comment by PinkiePieStyle** [comment] 2019-02-04 23:43
updated my adb
ive closed all emus/devices here  and found another bug
sdk_ver and android_ver doesnt work without dev/emu

**Comment by iGio90** [comment] 2019-02-05 00:09
a friend of me having this:
```
Traceback (most recent call last):
  File "C:\Users\James\Desktop\Dwarf\ui\ui_welcome.py", line 494, in update_dwarf
    self.update_dwarf_thread.on_status_text(self.on_dwarf_status)
TypeError: native Qt signal is not callable
```

**Comment by PinkiePieStyle** [comment] 2019-02-05 00:30
ive changed to connect in my comment
emit was wrong srry

**Comment by PinkiePieStyle** [comment] 2019-02-05 00:43
'Setup and run' in readme should have some windows related stuff

On Windows remove 'keystone_engine>=0.9.1.post3' in requirements.txt

pip3 install -r requirements.txt

and install the precompiled binarys

x86: https://github.com/keystone-engine/keystone/releases/download/0.9.1/keystone-0.9.1-python-win32.msi

or

x64: https://github.com/keystone-engine/keystone/releases/download/0.9.1/keystone-0.9.1-python-win64.msi

python3 dwarf.py

**Comment by iGio90** [comment] 2019-02-05 00:45
keystone is optional, there is code to check and eventually show a dialog if it's not installed so it could be safely removed from reqs. Yeah anyway, let's add those notes!

**Comment by PinkiePieStyle** [comment] 2019-02-05 16:18
why is there an reset hard 4h gone :/

**Comment by PinkiePieStyle** [comment] 2019-02-12 23:59
"Can this software be installed on my Windows 10?"
yes - can be closed here?

**Closed** 2019-05-11 11:24 UTC
